name: Linux

on:
  # Manual run
  workflow_dispatch:
    inputs:
      version:
        default: "102"
        required: true
        type: choice
        options: ["102", "115"]
  # Run on tag push
  push:
    tags: '[0-9][0-9][0-9].*-automation'

env:
  SCCACHE_GHA_ENABLED: "true"
  CCACHE: "sccache"
  VERSION: "${{ inputs.version && inputs.version || github.ref_name }}"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Get version to be made
      run: |
        var=${{ env.VERSION }}
        echo "VER=${var::3}" >> $GITHUB_ENV
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # remove the ones that are set to true
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: false
        docker-images: true
        swap-storage: false
    - name: init env
      run: |
        source ${{ env.VER }}/${{ env.VER }}.sh
        rustup override set $RUST_VER
        sudo apt update
        sudo apt install libdbusmenu-glib-dev libdbusmenu-gtk3-dev libdbusmenu-gtk-dev -y
        echo "ac_add_options --with-ccache=sccache" >> ${{ env.VER }}/mozconfig-Linux
        echo "ac_add_options --disable-elf-hack"  >> ${{ env.VER }}/mozconfig-Linux
    - name: Use sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3
    - name: build
      working-directory: ".."
      env:
        # Use build.sh on 102
        # TODO: hardcode `build-one-off.sh` when 102 is not needed anymore
        SCRIPT: "${{ (contains(env.VER, '102')) && 'build.sh' || 'build-one-off.sh' }}"
      run: |
        cp thunderbird-patches/build/${{ env.SCRIPT }} .
        echo "Y" | ./${{ env.SCRIPT }} ${{ env.VER }}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: linux-${{ env.VER }}
        path: "/home/runner/work/thunderbird-patches/mozilla-esr${{ env.VER }}/obj-x86_64-pc-linux-gnu/dist/betterbird-*.tar.bz2"
