name: Mac

on:
    workflow_dispatch:
      inputs:
        version:
          default: "102"
          required: true
          type: choice
          options: ["102", "115"]
    workflow_call:
      inputs:
        version:
          required: true
          type: string

  
env:
  SCCACHE_GHA_ENABLED: "true"
  CCACHE: "sccache"
  SCRIPT: "build.sh"

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: init env
      run: |
        source ${{ inputs.VERSION }}/${{ inputs.VERSION }}.sh
        rustup override set $RUST_VER
        brew install gnu-sed mercurial
        echo "ac_add_options --with-ccache=sccache" >> ${{ inputs.VERSION }}/mozconfig-Mac
    - name: Use sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3
    - name: build
      working-directory: ".."
      run: |
        cp thunderbird-patches/build/${{ env.SCRIPT }} .
        export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
        echo "Y" | ./${{ env.SCRIPT }} ${{ inputs.VERSION }}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: mac-${{ inputs.VERSION }}
        path: "/Users/runner/work/thunderbird-patches/mozilla-esr${{ inputs.VERSION }}/obj-x86_64-apple-darwin/dist/*.mac.dmg"
