name: Mac

on:
  # Manual run
  workflow_dispatch:
    inputs:
      version:
        default: "102"
        required: true
        type: choice
        options: ["102", "115"]
  # Run on tag push
  push:
    tags: '[0-9][0-9][0-9].*-automation'

env:
  SCCACHE_GHA_ENABLED: "true"
  CCACHE: "sccache"
  VERSION: "${{ inputs.version && inputs.version || github.ref_name }}"

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Get version to be made
      run: |
        var=${{ env.VERSION }}
        echo "VER=${var::3}" >> $GITHUB_ENV
    - name: init env
      run: |
        source ${{ env.VER }}/${{ env.VER }}.sh
        rustup override set $RUST_VER
        brew install gnu-sed mercurial
        echo "ac_add_options --with-ccache=sccache" >> ${{ env.VER }}/mozconfig-Mac
    - name: Use sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3
    - name: build
      working-directory: ".."
      run: |
        cp thunderbird-patches/build/build.sh .
        export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
        echo "Y" | ./build.sh ${{ env.VER }}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: mac-${{ env.VER }}
        path: "/Users/runner/work/thunderbird-patches/mozilla-esr${{ env.VER }}/obj-x86_64-apple-darwin/dist/*.mac.dmg"
