name: All builds

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
    linux-current:
        name: Linux 102
        uses: ./.github/workflows/linux.yml
        with:
            version: "102"
    mac-current:
        name: Mac 102
        uses: ./.github/workflows/mac.yml
        with:
            version: "102"
    # Comment out when not using it
    linux-next:
        name: Linux 115
        uses: ./.github/workflows/linux.yml
        with:
            version: "115"
    mac-next:
        name: Mac 115
        uses: ./.github/workflows/mac.yml
        with:
            version: "115"
